### PR TITLE
break stream if connection got aborted

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/19567

See https://github.com/nextcloud/server/issues/19567#issuecomment-1526328750

### CODE REVIEW

**Comment by staabm** [comment]
thanks for the patch. could you come up with a test case reproducing the initial problem ?

**Comment by yevon** [comment]
Any news about this one? Really interested in getting this fixed as this causes lots of issues on nextcloud.

**Comment by staabm** [comment]
> could you come up with a test case reproducing the initial problem ?

**Comment by yevon** [comment]
I'm just a nextcloud user that does use this lib indirectly. But in order to properly test this it should:

1 - Download a veri big file multiple times simultaneously.
2 - Interrupt connections unexpectedly, like a web browser close etc.
3 - Check that process count, or disk usage is 0 soon after connection interruption. Now it continues reading the file until it is read completely.

**Comment by szaimen** [comment]
Superceded by https://github.com/sabre-io/http/pull/207

**Pull request closed without merging**
