### PR TITLE
Break copying stream loop on failure

### PR DESCRIPTION
**Pull request by vfreex**
Try to mitigate the possibility of causing an infinity loop (https://github.com/owncloud/core/pull/36470, https://github.com/owncloud/files_primary_s3/issues/270, https://github.com/owncloud/files_primary_s3/issues/274), but I am not sure they are related.

Also includes https://github.com/sabre-io/http/pull/136.

### CODE REVIEW

**Comment by staabm** [comment]
@phil-davis can you confirm that this fix will prevent the endless loop reported?

**Comment by phil-davis** [comment]
@staabm @vfreex see https://github.com/owncloud/files_primary_s3/issues/274#issuecomment-559050410

@dpakach is looking into it. Hopefully we can give more detailed clues tomorrow.

**Comment by vfreex** [comment]
@phil-davis Thanks.
I want to add some points to the loop:
If it happens at https://github.com/sabre-io/http/blob/master/lib/Sapi.php#L111, it means the `left` didn't decrease and the copy actually failed for some reason. This PR adds a check and throw an exception if that happens. But why the copy fails may need further investigation.

**Comment by phil-davis** [comment]
@vfreex yes, at this point I assume that `stream_copy_to_stream` has some problem (it is just dealing with a 3-byte test text file that contains the text `123`), and why it specially has the problem when the back-end storage is S3 (not when running the test with local "ordinary" file storage), and why it works fine using the 5.0.2 code.

I guess the the 5.0.2 code did not have the loop structure. So maybe `stream_copy_to_stream` was returning `false` (or not the number of bytes streamed) but was actually streaming the correct bytes. The 5.0.2 code never checked the return value of `stream_copy_to_stream` so we never cared before. Now the loop depends on the return "bytes transferred" value.

Deepak can try all that in the morning.

**Comment by vfreex** [comment]
> Maybe error_get_last() could be used to identify the source of the problem (could be added to the exception message)

Do you mean put the error message into the exception? I didn't try `error_get_last()` and I am not sure if it can catch the error message for `stream_copy_to_stream`, but it worth a try.

**Comment by staabm** [comment]
I guess the fix for our underlying problem is provided with https://github.com/sabre-io/http/pull/138

Can anybody confirm?

**Comment by phil-davis** [comment]
> Can anybody confirm?

Yes, fixes hanging/CPU loop in ownCloud tests with S3 storage.

See my comments in https://github.com/sabre-io/http/pull/138#issuecomment-559562832

**Comment by staabm** [comment]
Closing, Since the underlying bug was fixed with https://github.com/sabre-io/http/pull/138

Nevertheless thank you @vfreex for your efforts. Very appreciated!

**Pull request closed without merging**
