### PR TITLE
Sending encoding="UTF-8" on basic auth challenges.

### LINKED ISSUE #69: Basic auth: use UTF-8 by default
In the past (since RFC 2617), there have been difficulties with non-US-ASCII characters in Basic auth credentials. Some clients use ISO-8859-1, some use UTF-8, and so on the server side. In reality, only US-ASCII characters are usable expect for proprietary solutions where clients and servers are tailored together.

Since RFC 7617, it's clear that UTF-8 is the future.

* `requireLogin()`: Please send `Basic realm="…",charset="UTF-8"` (see RFC 7617) on the server side in the 401 response, so that clients know that the server expects UTF-8 credentials.
* `getCredentials()`: Make sure that UTF-8 credentials are understood correctly.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Fixes #69. Thanks for the suggestion @rfc2822

### CODE REVIEW

**Comment by staabm** [comment]
it seems this PR fails for CS reasons.

**Comment by DeepDiver1975** [comment]
> it seems this PR fails for CS reasons.

yes - fixing it as we write ...

**Comment by DeepDiver1975** [comment]
hmmm .... hhvm is failing ....
https://travis-ci.org/sabre-io/http/jobs/342249288

I have 0 understanding of hhvm ... what to do? @staabm

**Comment by staabm** [comment]
hmm does it fail since this change or did it fail before?

**Comment by DeepDiver1975** [comment]
> hmm does it fail since this change or did it fail before?

seems to be failing for a longer time - will check

**Pull request merged**
